### ISSUE TITLE
Wording message erreur lors de l'inscription

### ISSUE THREAD

**Issue by myselfhimself** [jean-io/moncycle.app#1]
https://github.com/jean-io/moncycle.app/blob/b627f5912038d42e386a6fdc5a377afd33377c0a/www_data/inscription.php#L77

Ce message peut apparaitre dans les cas où l'email est malformatté ou bien dans le cas où un compte existe déjà et on essaye de le recréer. "vérifier votre adresse email" laisse entendre juste la bonne correction de l'adresse elle-même, plutôt qu'aller voir sa boîte mail pour un mail de notification de création de compte.

Est-ce qu'il ne faudrait pas dire, vérifiez "Merci de vérifer votre boite de réception (compte peut-être déjà créé) ou la bonne orthographe de l'adresse email que vous venez d'entrer." ? Certes c'est un peu longuet.

**Comment by jean-io** [comment]
Merci pour ce retour 🙂

Ce message apparaît aussi en cas de demande d'un nouveau mot de passe pour un compte qui n'existe pas. D'où "l'ambiguïté" du message qui lui permet d'être générique.

Pour corriger le problème il faut avoir un message par cas d'erreur. C'est pas grand chose à faire.

Il faut surtout éviter que le message d'erreur indique si un compte existe ou non pour éviter les fuites de données par énumération.

Je regarde tout ça dans quelques jours.
