### ISSUE TITLE
[Auto-hébergement] Liens dans les emails dysfonctionnels

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#11]
Les liens envoyés par email (par exemple, lors de la création du compte) sont codés en dur sur la version SaaS (tableau.moncycle.app)
https://github.com/jean-io/moncycle.app/blob/db49520e1402c63f0d7ce2011b5cd422622be36e/www_data/lib/mail.php#L38

Idéalement, il faudrait pouvoir remplacer tableau.moncycle.app par l'url sur laquelle l'application est hébergée.
Faut-il passer par une variable URL à configurer dans config.php, par exemple ?

**Comment by jean-io** [comment]
Oui en effet c'est un problème. Je vais ajouter un paramètre URL qui sera utilisé pour la création des liens.

**Comment by Limezy** [comment]
Merci !
