### ISSUE TITLE
Le choix "enceinte" semble clôturer le cycle par défaut

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#12]
Lorsque l'on crée une observation "enceinte", le cycle semble être clôturé par défaut (sinon je ne comprends pas bien comment se comporte l'UX - ma femme est actuellement enceinte). 
Je pense qu'il peut être intéressant, pour diverses raisons, de remplir certaines observations malgré la grossesse, et qu'il faudrait donc retirer ce comportement par défaut (ou l'annuler en paramètre ?)

**Comment by jean-io** [comment]
C'est voulu, ce paramètre enceinte a été conçu pour interrompre les observations pendant la durée de la grossesse et de l'allaitement. Ça évite d'avoir 12 mois de jours "à renseigner".

Les observations pendant une grossesse ne m'avaient jamais été demandé jusque-là. La solution (à ce jour) est de ne pas interrompre le suivi en renseignant le mode "enceinte" et d'activer ce paramètre que quand les observations seront terminés.

En tout cas félicitations pour la grossesse de votre femme 🥳
