### ISSUE TITLE
Notifications optionnelles

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#14]
Il pourrait être très pratique de pouvoir programmer une notification envoyée par la PWA sur le mobile (ou par le site sur le navigateur), par exemple à heure fixe, avec un message à rédiger soi-même et/ou en choisissant certains comportements pré-programmés. Exemple de cas d'usage ou de comportements utiles : 
* Un rappel tous les matins à 8h de ne pas oublier les observations
* En cas d'observation non remplies pour une journée N, rappel le matin N+1

**Comment by Limezy** [comment]
J'ai monté un petit workflow n8n qui teste la base de données et envoie des notifications via Ntfy mais c'est clairement "overkill" 😂

**Comment by jean-io** [comment]
Les notifications via navigateurs ne sont pas optimal. Il faudra attendre des vrais app sur les appstore, et c'est pas pour tout de suite 😞
