### ISSUE TITLE
Le symbole ⛰ ne s'affiche pas le jour J

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#18]
Si l'on coche le symbole jour sommet ⛰ le jour même, celui-ci ne s'affiche pas : à la place, un chiffre "0" apparaît, ce qui peut prêter à confusion. Il faut attendre le lendemain pour que le symbole ⛰ remplace le 0 et que le chiffre "1" apparaisse au dessus du premier jour post-sommet (ce qui est logique et compréhensible)

-> Il faudrait que le symbole ⛰ s'affiche en lieu et place du "0"

**Comment by jean-io** [comment]
Merci pour le rapport. J'arrive à reproduire.

**Comment by Limezy** [comment]
Merci !
