### ISSUE TITLE
Migration base de données

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#19]
Bonjour, 

J'ai tenté de mettre à jour l'application Yunohost pour moncycle.app.
Tout fonctionne correctement en cas d'installation à neuf.
Mais pour la mise à jour d'une installation existante, telle que sur mon serveur personnel, l'erreur ci-dessous apparaît :

```
  thrown in /var/www/moncycle/lib/db.php on line 439" while reading response header from upstream, client: 58.82.141.196, server: billings.mondomaine.fr, request: "GET /inscription HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-moncycle.sock:", host: "billings.mondomaine.fr", referrer: "https://billings.mondomaine.fr/connexion"
2023/12/04 09:20:08 [error] 3875749#3875749: *3685300 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'moncycle.jetton' doesn't exist in /var/www/moncycle/lib/db.php:439
Stack trace:
#0 /var/www/moncycle/lib/db.php(439): PDOStatement->execute()
#1 /var/www/moncycle/inscription.php(43): db_insert_jetton()
#2 {main}
```

Il manque apparemment une colonne à la base de données, et pour cela il faudrait probablement un genre de script simple de migration de la base. Un tel script existe-t-il ? Si oui je ne l'ai pas trouvé dans ce dépôt - pourriez-vous m'aider ?

Si non, pourriez-vous simplement m'indiquer la marche à suivre pour migrer la base ? 

Merci !

**Comment by Limezy** [comment]
Résolu avec une migration à la main !
https://github.com/YunoHost-Apps/moncycle_ynh/blob/70109b7ed14750d1ba14742d42d4eb14ac8c73f4/scripts/upgrade#L44-L52

**Comment by Limezy** [comment]
Je ferme le ticket

**Comment by jean-io** [comment]
Top si vous avez réussi à vous dépanner seul. Attention, si c'est la branche `master` que vous avez utilisé, des dev sont en cours, dites moi si il y a des problèmes de stabilité.

**Comment by Limezy** [comment]
Je comprends que je suis donc un peu en avance de phase par rapport à la version 7 officiellement sortie. 

Je pensais que le SaaS moncycle.app tournait sur la branche master mais ça n'est apparemment pas le cas ?

Si le SaaS continue de tourner sur la version 7 officiellement sortie en mars, je garderai probablement une version Yunohost "testing" à jour avec la branche master et une version Yunohost principale sur la base de la dernière sortie en date. 

Quoi qu'il arrive ce qui est fait n'est plus à faire et je remonterai les bugs ou instabilités ici si j'en trouve !

Merci encore pour ce formidable logiciel qui me sert au quotidien

**Comment by jean-io** [comment]
Il faut que je structure le projet avec une branche "stable" pour les release ou une branche "dev" non stable avec les dev en cours.
