### ISSUE TITLE
Les émoji sont perdues à l'export pdf

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#20]
**Cycle de test en vue standard**
<img width="348" alt="image" src="https://github.com/jean-io/moncycle.app/assets/24638389/2f0a6e81-50a4-4be9-9195-2ce6d4f3340b">

**Même cycle en export pdf**
<img width="378" alt="image" src="https://github.com/jean-io/moncycle.app/assets/24638389/6417b91f-6c0d-40c7-89d0-acc94fcc2164">

**Comment by jean-io** [comment]
Le truc sur ce bug c'est que les emojis ne peuvent pas être imprimé, il faudrait importer un police de caractère spécial emoji. Ce bug va pas être corrigé tout de suite 😞

**Comment by jean-io** [comment]
Ce bug ne sera pas corrigé, la library PHP permettant le créer des PDF ne permet pas de le faire. Je n'ai d’ailleurs jamais vu d'émojis dans des PDF. Ca restera donc une limitation de l’application...

**Comment by Limezy** [comment]
Ah, c'est amusant après une petite recherche je me suis justement dit que c'était tout à fait possible !
Il existe des librairies, notamment tFPDF (http://fpdf.org/fr/script/script92.php) qui est une extension de fpdf avec support des fontes unicode (et donc des émoji). Je crois que je vais tenter le petit défi et si j'y parviens je ferai une pull request.

**Comment by Limezy** [comment]
https://www.beaubus.com/blog/add_emoji_support_to_dompdf.html
Voici une piste intéressante en passant sur la librairie dompdf

**Comment by jean-io** [comment]
oui, j'ai hésité à passer sur dompdf mais il y a beaucoup de dépendances qui vont alourdir le projet alors que l'écrite des PDF au format HTML n'est pas nécessaire. Et je viens de tout réécrire avec FPDF donc c'est clairement pas à l'ordre du jour. Après @Limezy si tu te sens chaud de le faire, on s'appelle et je t'explique la structure du projet 😄

**Comment by Limezy** [comment]
Je garde l'idée dans un coin de la tête et te dirai le cas échéant !
