### ISSUE TITLE
[Résolu] Suppression cycles et autres

### ISSUE THREAD

**Issue by infocillasas** [jean-io/moncycle.app#23]
Bonjour,

Merci pour cette app !!
Je n'ai pas trouvé le moyen de supprimer un cycle.
Quand on ajoute un cycle Fertility, il dure 15j. par défaut, comment augmenter cette durée ?
Aussi, une documentation, meme succinte, sur l'utilisation, serzit bienvenue !

Romain

**Comment by jean-io** [comment]
Bonjour @infocillasas merci pour votre retour. L'application fonctionne avec sur la base base quotidienne et non sur une base de cycle. Ainsi à chaque cycle vous pouvez:

- créer un nouveau cycle en indiquant "nouveau cycle à cette date" :
![image](https://github.com/jean-io/moncycle.app/assets/4070933/4a3fe404-fa5d-4f9f-a81f-f6d13ba846f5)

- supprimer complement une observation journalière :
![image](https://github.com/jean-io/moncycle.app/assets/4070933/d5c07e59-aded-481d-b224-9c4b84786cbb)

- supprimer un cycle soit en supprimant supprimant la première observation de ce cycle, soit en décochant la case "nouveau cycle à cette date".

> Quand on ajoute un cycle Fertility, il dure 15j. par défaut, comment augmenter cette durée ?

Vous pouvez créer un cycle à la date que vous souhaitez mais vous ne pouvez pas créer un cycle dans le futur. La duré du cycle en court est calculé jusqu'à la date du jour.

Pour la documentation, ca demanderait beaucoup de travail et je préfère mettre l’énergie dans le développement. Cependant, un vidéo tuto est plus envisageable.

Est-ce que ca répond à vos questions ?

**Comment by infocillasas** [comment]
Bonjour @jean-io 
Oui c'est parfait merci beaucoup ! J'ai installé l'app en auto-hébergement en utilisant docker. J'ai du ajouter un container MariaDb dans le fichier docker-compose.yml pour que ca fonctionne. Impeccable !

**Comment by jean-io** [comment]
Top si vous avez pu l'installer via docker. La documentation est pas top, dites moi si vous rencontrez des problèmes. Et merci pour l'étoile 😄

**Comment by jean-io** [comment]
@infocillasas et @Limezy lors de votre prochain upgrade il faudra modifier la BDD, il y a un script pour vous aider: https://github.com/jean-io/moncycle.app/blob/master/db/migration/v7_vers_v8.sql

A dispo si besoin.

**Comment by Limezy** [comment]
Bien noté merci @jean-io !

**Comment by Limezy** [comment]
Je viens de terminer la migration de l'application Moncycle.app Yuohost vers la version 9
Les migrations de base de donnée sont fonctionnelles
Merci encore

**Comment by infocillasas** [comment]
Idem, migrations faites, merci @jean-io
