### ISSUE TITLE
Erreur 404 sur le lien de démo

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#24]
Le lien de la page principale vers la démo aboutit à une erreur 404. 
Le compte de démo en lui-même fonctionne. 
Je n'ai pas vérifié pour ne pas tout casser, mais n'y a-t-il pas un risque qu'un utilisateur active le 2FA sur le compte de démo et la rende ainsi inutilisable pour les autres ?
Merci pour la v8 !

**Comment by jean-io** [comment]
Bien vu @Limezy  ! c'est corrigé dans ce commit : https://github.com/jean-io/moncycle.app/commit/5738e79f852ca06314d9a0bb09ea7b31939cab0b

Pour la démo, un cron la réinitialise toutes les heures. C'est en effet un risque, mais il est aussi present si un utilisateur change le mdp. Au pire, les utilisateurs seront "dérangé" pas plus d'une heure. moncycle.app décolle bien mais pas au point d'avoir en permanence plus de deux personnes par heure sur la démo.
