### ISSUE TITLE
Le retour en vue maxi active la visibilité de tous les cycles par défaut

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#26]
# Problème
1. Lors du login -> la vue par défaut est en vue "maxi" sur le cycle en cours
2. Cliquer sur "vue mini" -> la totalité des cycles est visible (cela semble logique et utile pour comparer les cycles)
3. Cliquer sur "vue maxi" -> tous les cycles sont visibles en vue maxi, ce qui commence à devenir compliqué quand le volume d'observations devient conséquent (personnellement j'ai déjà plus d'un an dans l'appli) car il faut naviguer jusqu'en bas pour retrouver la date en cours

# Solutions
1. Solution 1 : restreindre le retour en "vue maxi" au cycle en cours. Il reste toujours le bouton "cycle précédent" si on veut voir plus d'un cycle
2. Solution 2 : (peut-être la plus ergonomique ? À tester) garder la totalité visible mais mettre les dates "à l'envers" avec la date d'aujourd'hui tout en haut. On pourrait imaginer cette vue "à l'envers" comme la vue par défaut avec éventuellement un bouton pour "retourner" le sens du temps

**Comment by jean-io** [comment]
Merci pour ce retour. Oui je confirme le problème. En plus des solutions proposées, il y a d'autres possibilités : 
- dissocier le chargement des observations entre les deux vues
- masquer les cycles dans la vue maxi quand ils sont chargés dans la vu mini (masqué au sens du bouton "masquer" présent dans la vue maxi)
- faire un bouton flèche fixe pour descendre en bas de page et vitre retrouver un repère quand on retourne dans la vu maxi

@Limezy ton avis?

**Comment by Limezy** [comment]
Bonjour @jean-io, je me suis fait un compte de démo avec 800 observations et j'ai constaté qu'en l'état les choses deviennent rapidement inutilisables après 2 ans ou plus d'observations. Je ne vois pas trop l'intérêt d'un bouton pour descendre sachant que justement les infos importantes sont toutes en bas, et plus le temps passe moins les premières observations les plus lointaines dans le passé sont intéressantes (surtout à l'échelle de 2 ans, 5 ans, 10 ans...!).

**Voici des propositions concernant l'UX :** 
1. Pour toutes les vues verticales, renverser le temps avec les observations les plus récentes / les cycles les plus récents en premier. C'est plus logique et ça permet d'avoir l'observation du jour tout en haut, très facilement accessible
2. Plutôt que de dissocier les vues mini / maxi, les unifier et faire en sorte que n'importe quel cycle puisse être soit en vue mini horizontale (temps de gauche à droite), soit en vue maxi verticale (temps de haut en bas), soit en vue masquée
3. Permettre dans les paramètres du compte de choisir un nombre N-1 de cycle visibles par défaut, et mettre par défaut le cycle en cours en maxi et les N-1 autres cycles en mini, le reste invisible
4. Comme pour la plupart des sites web maintenant, faire en sorte que si on arrive en bas de la page, les cycles précédents (s'ils existent) se chargent au fur et à mesure du "scroll". Ça permet d'économiser le bouton "cycles précédents" et ça rend tout ça plus naturel
5. Garder en haut deux boutons "Tout minimiser" / "Tout maximiser"

**Quelques maquettes rapides**
1. Vue inversée des observations
<img width="456" alt="image" src="https://github.com/jean-io/moncycle.app/assets/24638389/44757fd3-8fb3-4687-84b0-dcefebe3618c">

2. Vue inversée des cycles
<img width="469" alt="image" src="https://github.com/jean-io/moncycle.app/assets/24638389/7954e97c-b5d6-4fb8-92e2-3a97ee5b6b53">

**Comment by Limezy** [comment]
Génial! Je teste ça tout de suite et je te fais un retour. Je suis impressionné par la vitesse de développement 🤩

**Comment by jean-io** [comment]
Merci. J'ai un peu de temps le soir en ce moment, mais ça va pas durer.

> Sur un téléphone, la vue mini est trop petite pour être précise avec les doigts. On gagnerait peut-être en UX à faire en sorte qu'un clic sur un cycle en vue mini le développe verticalement plutôt que d'ouvrir au hasard une des observations

Réorganiser en ce sens demande de revoir en profondeur l'UI. C'est pas pour toute suite. Par contre, des boutons ont été ajoutés dans le menu de modification d'une observation pour naviguer plus facilement sans avoir à fermer le menu.

**Comment by Limezy** [comment]
> Hello @Limezy les solutions retenues qui ont permit de fix sont les suivantes:
> [...]

Je viens de tester et migrer mon instance perso, merci c'est vraiment plus fonctionnel comme interface !
Petit bonus, l'appli est encore plus réactive car seulement un cycle se charge par défaut avant le scroll.
Bravo !

**Comment by jean-io** [comment]
Oui il y a pas que ca, les cycles sont stocké localement ce qui donne l'illusion d'un chargement instantané. Ca augmente énormément la sensation de fluidité.
Merci pour l'idée du scroll infini et d'inverser l'ordre des observations car je n'y avait pas pensé 👍🏻 

Attention, je viens de faire un commit qui résous plein de petits problème notamment une boucle infini à l'export PDF. On est à 1 ou deux jours max de la v10 ! pour l’anniversaire des 3 ans de l'appli ! 🍾
