### ISSUE TITLE
L'export des données pourrait comporter un dump sql

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#28]
Il serait utile d'ajouter un dump sql des données dans l'archive de l'export dans l'UX ou de l'appel d'API /mes_donnees_svp.

Cela permettrait de couvrir quelques cas d'usage, tels que : 
* L'export des données depuis moncycle.app pour les importer dans une instance auto-hébergée, ou vice-versa
* La recréation d'un compte utilisateur par l'admin si celui-ci change d'avis ou a fait une fausse manipulation etc...

**Comment by jean-io** [comment]
Oui c'est une super idée ! Sur l'export c'est facile, par contre pour l’import, je ne sais pas comment faire évitant les failles de sécurité: il faut que l'utilisateur ne puisse pas écrire sur le compte d'une autre personne.

**Comment by Limezy** [comment]
Merci pour ta réponse !

- À court terme, l'idée d'avoir le dump à l'export et de pouvoir le faire réinjecter en base manuellement par l'administrateur de l'instance (via l'émail de support par exemple) semble déjà très satisfaisant
- À moyen ou long terme, on pourrait mettre sur pied un schéma JSON standard de suivi de cycle (éventuellement compatible avec l'arborescence https://schema.org) et un mécanisme d'export dans ce format / import depuis ce format. Cela permettrait aussi, par exemple, d'exporter juste un cycle pour l'envoyer aux moniteurs. Mais il faut reconnaître que le rapport temps passé / gains à l'usage semble très faible par rapport à l'option court terme...

**Comment by jean-io** [comment]
Il y a un sujet plus global: comment créer un format standard de partage d'un cycle menstruel. Dans ce cas, c'est pas moncycle.app tout seul.

**Comment by Limezy** [comment]
J'ai trouvé cette piste https://help.flo.health/hc/en-us/articles/360054973811-How-do-I-export-my-data#:~:text=We%20can%20export%20your%20Flo,application%20that%20supports%20this%20feature. à explorer.
Quitte à utiliser un format, il faudrait qu'il soit compatible avec ce genre de grosses applications car en effet, il y a peu de chances que moncycle.app puisse lancer à lui-seul un tel type de format standard !

**Comment by jean-io** [comment]
Les réflexions sur le format de fichier d'import export sont déporté dans le projet **fertility-cycle-file-format** 🙂
