### ISSUE TITLE
L'export des données n'est pas un danger

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#29]
Le bouton d'export des données est placé dans la section "Zone de danger"

<img width="683" alt="image" src="https://github.com/jean-io/moncycle.app/assets/24638389/c2360023-aa25-464f-8c44-1b317e35f8df">

L'export des données n'est pas un danger, au contraire il vaut mieux avoir récemment exporté ses données en cas de fausse manip ! Il serait probablement pertinent de déplacer ce bouton dans une autre section de la page "Mon compte"

**Comment by jean-io** [comment]
il y a un bouton de confirmation, si on appuie sur `supprimer définitivement mon comte` ce n'est pas assez ?

**Comment by jean-io** [comment]
duplicate #30

**Comment by Limezy** [comment]
> il y a un bouton de confirmation, si on appuie sur `supprimer définitivement mon comte` ce n'est pas assez ?

En effet, mais ce n'était pas exactement mon point dans cette "issue".
Mon point était simplement de dire que la fonction d'export n'est pas un danger en soi.
Si le bouton "exporter" est mis dans la zone danger, cela sous-entend pour l'utilisateur qu'il y a un danger à l'utiliser !
La zone danger devrait uniquement comporter des boutons menant à des actions destructives, comme la suppression du compte actuellement.

**Comment by jean-io** [comment]
corrigé dans fe6d093669ad5441f559ac358f30d0d98d1257d6
