### ISSUE TITLE
Package Yunohost ?

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#3]
Bonjour, merci pour cette application que je découvre grâce au SB. Avec votre autorisation je pourrais en faire un package Yunohost, pour ceux qui voudraient auto-héberger facilement leur propre instance ?

**Comment by jean-io** [comment]
Bonjour, oui il y a pas de soucis, au contraire, toutes les contributions sont les bienvenues. A terme, j'aimerai aussi publier une image dans le hub Docker. Beaucoup d'idée, mais peu de temps ... :)

**Comment by Limezy** [comment]
Je lance donc le package Ynh et vous dirai lorsqu'il sera fonctionnel / testé / ajouté au catalogue officiel !

**Comment by Limezy** [comment]
Pour référence et suivi : https://github.com/YunoHost-Apps/moncycle.app_ynh

**Comment by Limezy** [comment]
I have nearly managed to get a working version of moncycle.app on a test server.
The main challenge is to move from Apache to Nginx.

**Comment by jean-io** [comment]
Be careful because `script` directory should be protected by a password. Make sure that this directory is not available to the world.

**Comment by Limezy** [comment]
Bien noté merci. Pardon pour le passage en anglais ! Je travaille au quotidien en anglais et je ne m'en suis même pas aperçu. 

Tout fonctionne sur mon serveur de test sauf une chose : l'application ne passe pas en plein écran quand je l'installe en mode "PWA" (sur un iPhone, je n'ai pas d'Android pour tester). Avez-vous une configuration spécifique quelque part pour forcer le mode en plein écran ? C'est peut être une perte due au passage Apache -> nginx ?

**Comment by Limezy** [comment]
Deux captures d'écran, l'une de moncycle.app l'autre de mon serveur pour comparaison

![image](https://user-images.githubusercontent.com/24638389/213437577-648ee16e-a245-4f09-a3aa-b683c5d670f8.jpeg)

![image](https://user-images.githubusercontent.com/24638389/213437624-c65fd09f-ab6f-47ba-ac1c-83751d30529b.png)

**Comment by jean-io** [comment]
> Avez-vous une configuration spécifique quelque part pour forcer le mode en plein écran ? C'est peut être une perte due au passage Apache -> nginx ?

Non tout est configuré via des métas HTML, en l’occurrence: https://github.com/jean-io/moncycle.app/blob/655ba524a3bf664c5f230812efc0932dfc5416bc/www_data/vue/head.html#L5

Il y a une astuce cependant: il faut ajouter l'APP sur l'écran d’accueil une fois connecté. Dites moi si ca marche toujours pas.

**Comment by Limezy** [comment]
En effet, cela fonctionne ! 
Merci,je vais donc pouvoir commencer à coder le package Yunohost

**Comment by Limezy** [comment]
Il n'y a aucune obligation, mais si vous faites des "release" de votre application en leur donnant des numéros 0.1, 0.2 etc... Ça facilitera la numérotation du package Yunohost correspondant ainsi que les mises à jour

**Comment by Limezy** [comment]
> Be careful because `script` directory should be protected by a password. Make sure that this directory is not available to the world.

https://github.com/Limezy/moncycle.app_ynh/blob/3b3b477f794263584b1d754a8e7580107a792adf/conf/nginx.conf#L12-L15

Done ✅

**Comment by jean-io** [comment]
Super. Pour que les cycles soient envoyé par mail automatiquement à la fin de ceux-ci, il faut que le fichier `script/cron.php` soit exécuté via cron à une fréquence de 1x par jour (la fréquence peut être moins élevé mais pas plus).

**Comment by Limezy** [comment]
Bien noté. En effet, c'est pratique ! J'ai dû faire un petit patch pour envoyer les emails en localhost sans authentification TLS, mais on va laisser ça au niveau du package Yunohost plutôt que de modifier de dépôt en amont.
https://github.com/Limezy/moncycle.app_ynh/blob/master/sources/patches/app-01-mail.patch
Je devrais pouvoir lancer les premiers tests sur le CI Yunohost dev ce WE

**Comment by Limezy** [comment]
Tout est fonctionnel sur mon serveur de test :
* Installation (derrière le SSO ou non, sur une racine domaine ou chemin)
* Backup
* Restauration
* Mise à jour
* Suppression
* Changement d'URL
* Cron
* Dossier script protégé
* Envoi des emails

https://github.com/YunoHost-Apps/moncycle.app_ynh/pull/1
J'ai lancé le CI mais il est un peu sous l'eau en ce moment - probablement 2 ou 3 jours avant d'avoir le résultat.

**Comment by jean-io** [comment]
Bravo! et merci pour le travail. Dès que c'est mergé, je cloture le ticket.

> mais on va laisser ça au niveau du package Yunohost plutôt que de modifier ce dépôt en amont

A terme si il y a plus de demande, on pourra modifier.

**Comment by Limezy** [comment]
Moncycle.app a été ajouté au catalogue Yunohost
https://github.com/YunoHost/apps/pull/1617

La branche "testing" du package est 100% fonctionnelle et testée.
J'attends le résultat du CI avant de fusionner sur la branche master.
D'ici quelques jours l'application sera disponible dans le catalogue Yunohost et affichée comme fonctionnelle / niveau 7.
Je clôturerai alors ce ticket.

Pour les prochaines étapes (tout ceci est évidemment optionnel et à votre discrétion @jean-io :
* Ajout d'une mention concernant l'auto-hébergement pour ceux qui le souhaitent, voire un bouton type [![Installer Moncycle avec YunoHost](https://install-app.yunohost.org/install-with-yunohost.svg)](https://install-app.yunohost.org/?app=moncycle) (c'est normal si ce lien pointe vers une alerte pour le moment, il faut attendre quelques jours que le catalogue se régénère et prenne en compte le niveau 7 de l'application
* Ajouter quelques tests php pour changer selon le contexte (auto-hébergé ou SaaS sur votre serveur OVH) quelques actions utilisateurs, par exemple les cases "RGPD" à cocher (dans la pratique, il n'y a pas de données envoyées sur le serveur moncycle.app lorsque l'utilisateur est hébergé. Mais il peut être utile d'ajouter une case à cocher comme quoi il est responsable de ses données / sauvegardes, et il ne peut pas tenir rigueur à moncycle.app d'une quelconque perte en la matière)

Pour info, il y a une réflexion en cours au sein de l'équipe Yunohost sur le sujet, mais à date il n'y a pas de système de mesure d'audience pour les différents package : vous ne serez donc pas en mesure de savoir combien de personnes ont installé moncycle.app sur leur propre serveur.

**Comment by jean-io** [comment]
Oui très bien, je vais rajouter ça sur le site de présentation. Je vous propose de clôturer l'issue quand ce sera fait.

Encore merci pour cette contribution 🙂

**Comment by Limezy** [comment]
Parfait ! 
Le catalogue Yunohost est régénéré tous les vendredi. Je pense que tout sera opérationnel côté Yunohost ce week-end. 
Avec plaisir - je l'ai aussi fait pour moi 😀 
Merci pour ce projet, parfaitement adapté à mes besoins

**Comment by Limezy** [comment]
Re-bonjour @jean-io 
Sur mon instance en mode PWA je suis systématiquement déconnecté de ma session après quelques heures.
Auriez-vous une idée de ce qui pourrait être mal configuré ?

**Comment by jean-io** [comment]
Oui ce sont les sessions PHP qui gères le temps de connexion, il faut donc modifier le temps d'expiration des sessions et des cookies des sessions.

Dans le répertoire des conf server du repo, il y en a un pour php. Ce sont ces lignes qui sont importantes : 

´´´ini
; sessions de 30 jours
session.gc_maxlifetime = 2592000
session.cookie_lifetime = 2592000
´´´

**Comment by Limezy** [comment]
Merci beaucoup, j'ai enfin réussi à prendre le temps pour corriger ça. L'application est maintenant 100% fonctionnelle, intégrée au catalogue Yunohost, et niveau 7 (elle atteindra le niveau maximum, 8, après 6 mois sans baisse de qualité).
Je propose, soit de fermer ce ticket directement, soit de pousser un petit PR sur le readme de ce repo (et/ou sur le site principal) proposant d'installer l'application via Yunohost (par exemple, avec un message comme ci-dessous) 

> Pour auto-héberger Moncycle.app, vous pouvez utiliser Yunohost 
> [![Install Moncycle with YunoHost](https://install-app.yunohost.org/install-with-yunohost.svg)](https://install-app.yunohost.org/?app=moncycle)

C'est absolument sans aucune obligation, vous me dites !

**Comment by jean-io** [comment]
Top merci @Limezy
Avez-vous la possibilité de renommer la paquet de "Moncycle" vers "moncycle.app" ? Ca permettrait à ce que ce soit plus clair pour les utilisateur.
Ok pour une PR vers le readme du repo.

**Comment by Limezy** [comment]
Parfait, je fais une PR vers le readme du repo et je fermerai ce ticket.
Pour ce qui est de renommer le paquet vers moncycle.app, j'ai tenté mais cela induisait malheureusement quelques problèmes pour l'écosystème Yunohost, voir les discussions ici : https://github.com/YunoHost/apps/pull/1617#pullrequestreview-1264193819 (ouvrir le fil de commentaire résolu).
