### ISSUE TITLE
La suppression du compte est "trop" accessible

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#30]
La suppression du compte est accessible d'un simple clic dans la page "Mon compte".
Malgré les signaux d'alerte (Zone de danger) et la couleur rouge, en soi un simple clic non voulu ou décalage de la souris quand on veut exporter ses données et paf... c'est déjà trop tard !

Il serait probablement utile de valider la supression du compte par une phrase à écrire dans un champ par l'utilisateur, comme cela est fait par exemple sur Github pour supprimer un dépôt de code (capture d'écran trouvée sur le net). Par exemple "Oui, je suis sûr de vouloir supprimer mon compte et toutes mes données associées". Idem, cette phrase pourrait être requise comme un paramètre lors de l'appel d'API /supr_compte

<img width="931" alt="github-delete-repository-image7" src="https://github.com/jean-io/moncycle.app/assets/24638389/05b0b62c-c403-4aba-9343-022bb81a8c4c">

**Comment by jean-io** [comment]
Il y a une confirmation (oui/non) qui est demandé à l'utilisateur. Par contre je me disais que ca serait pertinent de demander le mot de passe pour la suppression.

**Comment by jean-io** [comment]
Il faut globalement retravailler cette section **zone de danger**

**Comment by Limezy** [comment]
> Il y a une confirmation (oui/non) qui est demandé à l'utilisateur. 

Ah oui en effet, désolé je n'avais pas vu ça

> Par contre je me disais que ca serait pertinent de demander le mot de passe pour la suppression.

Bonne idée !

**Comment by jean-io** [comment]
La solution:
![image](https://github.com/jean-io/moncycle.app/assets/4070933/6e85857b-c5ff-4bcc-9213-e723bbdb2749)
