### ISSUE TITLE
Mauvaise nouvelle pour les utilisateurs iOS

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#31]
https://developer.apple.com/fr/support/dma-and-apps-in-the-eu/
<img width="760" alt="image" src="https://github.com/jean-io/moncycle.app/assets/24638389/6767af8e-9f3b-43a1-95ba-d48eed57105a">
https://www.igen.fr/ios/2024/02/ce-nest-pas-un-bug-ios-174-va-liquider-les-web-apps-pwa-en-europe-142005

**Comment by Limezy** [comment]
Il y a deux problèmes pour passer sur une app native iOS : 
La partie technique - même s'il semble exister des solutions relativement simples type https://cordova.apache.org
La partie financière - $99 par an pour un compte développeur

**Comment by jean-io** [comment]
Merci @Limezy pour la vigilance, j'imagine que maintenant on a plus le choix, on va devoir aller sur les app store. C'est une mauvaise pour les dev, moins pour les utilisateurs qui ont toujours eu du mal à comprendre le concept d'une app pas dans un app/play store...

Par contre ca va impliquer une restructuration du code sur GitHub... entre le back-office, le front, e site web de représentation, docker, yunohost, et maintenant les app "native" ... je vais devoir créer une organisation.

**Comment by Limezy** [comment]
> Merci @Limezy pour la vigilance, j'imagine que maintenant on a plus le choix, on va devoir aller sur les app store. C'est une mauvaise pour les dev, moins pour les utilisateurs qui ont toujours eu du mal à comprendre le concept d'une app pas dans un app/play store...

Tout à fait d'accord ! Je trouve simplement dommage que Apple mette la barrière à l'entrée aussi haute à 99 dollars par an, surtout pour les développeurs souhaitant offrir une application gratuite. Au passage, ça me fait penser à un point pour la partie financière -> j'utilise l'app tous les jours et ça me semble normal de contribuer. Pour diverses raisons pratiques je préfère contribuer via le sponsoring github que via Tipeee. Est-ce possible d'ouvrir le sponsoring sur ce dépôt ? Si non, je m'inscrirai sur Tipeee, pas de problème.

> Par contre ca va impliquer une restructuration du code sur GitHub... entre le back-office, le front, e site web de représentation, docker, yunohost, et maintenant les app "native" ... je vais devoir créer une organisation.

En effet... J'espère que le boulot ne sera pas trop important et je pourrai aider s'il le faut, dans la mesure limitée de mes compétences !

**Comment by jean-io** [comment]
Je clos car il s'agit plus d'une discussion. Il faudrait peut être que j'active la discussion sur le repo.

**Comment by Limezy** [comment]
La bonne nouvelle du jour pour fêter les 3 ans de l'appli et la v10 juste sortie ! 

https://www.igen.fr/ios/2024/03/surprise-ios-174-va-finalement-maintenir-les-pwa-en-europe-142251

Cela dit les remarques ci-dessus restent vraies, je peux éventuellement essayer de retravailler la partie "tuto" pour expliquer aux utilisateurs comment installer Moncycle.app comme une PWA sur leur iPhone

**Comment by jean-io** [comment]
oui ouf ! 😄 clairement je garde l'idée de l'app iOS et Android avec Cordova.

J'ai essayé de me pencher sur les service worker pour rendre l'app hors ligne, mais j'ai pas tout compris 🤦🏻‍♂️ 
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Offline_Service_workers

> je peux éventuellement essayer de retravailler la partie "tuto" pour expliquer aux utilisateurs comment installer Moncycle.app comme une PWA sur leur iPhone

Ca serait top car cette parti du site de presentation a vraiment été fait à la va-vite!
![image](https://github.com/jean-io/moncycle.app/assets/4070933/8141149b-7db1-4362-9f09-af66d694c0c6)
