### ISSUE TITLE
Masquer puis afficher un cycle laisse un espace blanc

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#33]
(sur le dernier commit en date [ee19dce](https://github.com/jean-io/moncycle.app/commit/ee19dce2c74ff6e948fae98319cd00eda6ce4117))

<img width="808" alt="image" src="https://github.com/jean-io/moncycle.app/assets/24638389/21e92d93-0327-4da4-9f05-8cb6e3916276">

**Comment by jean-io** [comment]
La console JavaScript affiche pas d'erreur ?

**Comment by Limezy** [comment]
* Pas d'erreur dans la console
* Capture de l'inspecteur ci-dessous
* Sur Safari 17.0
* J'ai réussi à reproduire sur Chrome

<img width="1247" alt="image" src="https://github.com/jean-io/moncycle.app/assets/24638389/aee83f6f-bfe9-4675-8617-c1eedc5eca41">

**Comment by jean-io** [comment]
j'ai réussi à reproduire c'est bon.
