### ISSUE TITLE
Passer en vue maxi directement ne charge pas tous les cycles une fois en vue mini

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#34]
1. Se connecter -> vue maxi par défaut
2. Directement cliquer sur "vue mini"
3. Seulement quelques cycles sont affichés (6 cycles dans mon cas) et impossible de "scroller" vers le bas pour en afficher plus
4. Si je reviens en vue maxi, que je scrolle vers le bas puis retourne en vue mini, tous mes cycles sont affichés

**Comment by jean-io** [comment]
C'est résolu dans le prochain commit. Jouer avec la taille de la fenêtre pour forcer l'affichage d'une bar de navigation devrait aider (jusqu'à la correction).

**Comment by Limezy** [comment]
Je n'arrive pas à reproduire avec le compte de démo qui ne comporte que deux cycles.
Je pense qu'il faut "trop" de cycles pour "dépasser" de la page en vue mini

**Comment by jean-io** [comment]
@Limezy est-ce que le dernier commit a permis de corriger? (je viens de commit)

**Comment by Limezy** [comment]
Je teste demain matin ! (Je suis sur un créneau horaire asiatique)

**Comment by Limezy** [comment]
Je confirme que le bug est résolu 👍
