### ISSUE TITLE
Sur téléphone (iOS) en vie maxi, les émoji sont décalées vers le bas

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#35]
![IMG_8009](https://github.com/jean-io/moncycle.app/assets/24638389/eda4abe0-6124-4d0e-82e1-97fb192ea032)

**Comment by jean-io** [comment]
Je viens de commit. À voir si ça règle le problème 🤔

**Comment by jean-io** [comment]
je viens de réussir à reproduire le bug.

**Comment by jean-io** [comment]
Bon en fait non je n'arrive pas à reproduire 😞 
![image](https://github.com/jean-io/moncycle.app/assets/4070933/8278e84a-ddb9-4522-bc6f-8acf99116bf2)

**Comment by Limezy** [comment]
L'erreur reste présente sur le dernier commit, sur un iPhone 13 mini. Je regarde ce soir si elle peut être reproduite dans le simulateur iPhone XCode

**Comment by Limezy** [comment]
Je reproduis également sur les simulateurs iPhone 13, iPhone 15, iPhone SE 3e génération...
