### ISSUE TITLE
La démo Fertility Care avec température ne comporte pas de températures

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#36]
Sur le dernier commit.

De plus, le dernier cycle en date de la démo Billings n'a pas de température non plus, ça peut prêter à confusion quand on découvre l'app puisque c'est... le premier cycle que l'on voit maintenant !

**Comment by jean-io** [comment]
Oui c'est normal, l'app ne permet pas une bonne interpretation des courges de température, tant que c'est pas le cas, je ne vais pas valoriser cette feature. Pour FertilityCare normalement il y a pas de suivi de température, c'est donc normal (la température est même pas dans l'export PDF).

Il faudrait que j'introduise des constantes dans le code PHP pour qu'il soit plus propre: voici à quoi corresponde les le champ méthode dans la BDD: 
1. Billings + température (symptothermie pauvre)
2. Billings
3. FertilityCare
4. FertilityCare + température (cas entartrement rare)

C'est fait exprès que les démo soit 2 et 3 donc sans température.

Concernant la prise de température, et des lignes liés à leur interpretation, elle ne sont pas prévu. Si des gens on besoin de ca en SaaS j'aurai tendance à les diriger vers https://cyclefeminin.net qui a fait un énorme boulot là dessus avec une vrai connaissance médicale que j'ai pas.

**Comment by Limezy** [comment]
> Oui c'est normal, l'app ne permet pas une bonne interpretation des courges de température, tant que c'est pas le cas, je ne vais pas valoriser cette feature. Pour FertilityCare normalement il y a pas de suivi de température, c'est donc normal (la température est même pas dans l'export PDF).

Ma femme et moi utilisons Billings donc je n'y connais rien sur les interprétations de courbes de température.
Par curiosité, quelles seraient les fonctions manquantes pour proposer une "bonne interprétation" au sens des méthodes symptothermiques ? Simplement des champs supplémentaires de commentaires sur les températures ?

> C'est fait exprès que les démo soit 2 et 3 donc sans température.

OK bien compris !

**Comment by jean-io** [comment]
Nous utilisons aussi Billings.

> Par curiosité, quelles seraient les fonctions manquantes pour proposer une "bonne interprétation" au sens des méthodes symptothermiques ? Simplement des champs supplémentaires de commentaires sur les températures ?

En soit vis à vis des observations quotidiennes non, mais il faut ajouter un certain nombre de lignes pour identifier les points hauts et bas. Ces lignes sont liées au cycle et la base de données de moncycle.app ne permet pas de sauvegarder d'attributs sur les cycles (il y a pas de table cycle, la création d'un nouveau cycle est seulement un attribut de l'observation du premier jour du cycle).

![image](https://github.com/jean-io/moncycle.app/assets/4070933/5f379e20-75d1-4162-94cf-4b7b0e3de16c)

Autre analyse de moncycle.app et la symptothermie: https://m.facebook.com/story.php?story_fbid=pfbid02ZpBj6AT6jfDYF3Fu8CXF7pvaiDFpQh8WN5skUckBJ4PFPRzscztEEtsDDNVBzftYl&id=690719304635355
