### ISSUE TITLE
vue mini: numérotation des jours non adaptée

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#39]
Tout d'abord, merci beaucoup pour les mises à jour et corrections de bug en tous genres.
Le package Yunohost est à jour.

Je ne suis pas très "fan" de l'affichage du numéro de jour en format mini : 
* Premièrement ça me semble être un peu contradictoire avec le but qui est d'afficher les cycles dans un format très compact (= beaucoup de cycles) et facilement comparable d'un cycle à l'autre. C'est d'ailleurs une visualisation qui n'a pas vraiment d'équivalent dans d'autres apps du style et une vraie valeur ajoutée !
* Deuxièmement, en cas de cycle très long (retour de couches notamment) et sur un téléphone, les numéros de jour se chevauchent (voir capture ci-dessous)
![IMG_8183](https://github.com/jean-io/moncycle.app/assets/24638389/5024c344-aa17-40c1-ba48-fe75e39dde8b)

**Propositions :** 
* Rendre l'affichage des numéros de jours optionnel dans les paramètres (par exemple en dessous de "Afficher les dates en ordre croissant...")
* Mettre un bouton permettant d'afficher ou non les jours en vue mini entre "vue maxi" et "Mon compte"
* Mettre une "réglette" avec les jours de 1 à 35, qui serait fixe et resterait en haut (comme la réglette sur Word par exemple, je peux faire une maquette pour montrer)

**Comment by jean-io** [comment]
Merci @Limezy je n'ai pas pensé aux cycles qui durent plus de 100 jours... à la réglette fixe type Excel me semble être la bonne solution.

**Comment by jean-io** [comment]
Ajouter dans les commit du jour. @Limezy utilise plutôt la branch stable pour mettre à jour les packages sur yunohost

**Comment by Limezy** [comment]
Je vais garder la branche "testing" du package Yunohost à jour, et en effet garder la branche "master" du package alignée sur la branche stable de ce repo, bonne idée !
