### ISSUE TITLE
Coquilles

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#4]
Bonjour,
Il y a quelques coquilles ou erreurs de grammaire. Peut-être pourriez-vous envisager de migrer l'ensemble des parties écrites sur une plateforme telle que Crowdin ? Cela permettrait de les corriger facilement de façon collective, et peut-être pour certains de traduire l'application dans d'autres langues.

**Comment by jean-io** [comment]
Bonjour Limezy,
L'app a été construite avec peux de temps/ressources. Dans le fond je suis à 200% pour utiliser un produit comme Crowdin. A date, il y a d'autres priorités: commenter le code, documenter l'API avec la mise en place d'un swagger, fortement perfectionner la courbe des températures...
Pouvez-vous corriger les fautes avec une PR GitHub ?

**Comment by Limezy** [comment]
> Pouvez-vous corriger les fautes avec une PR GitHub ?

Je comprends évidemment ! Bravo pour ce projet.
J'ai fait une PR pour le code actuellement dispo sur GH. #5 
Apparemment le code de la page d'accueil n'est pas dans ce dépôt : je vous ai néanmoins ajouté les corrections proposées en commentaire du PR. #5

**Comment by jean-io** [comment]
Merci je vais regarder la PR, pour le code sur la page d’accueil, vous le trouverez dans la branche "webpage" ;)

**Comment by jean-io** [comment]
Coquilles corrigées dans #5 #8 et #6
