### ISSUE TITLE
Propositions pour améliorer l'affichage de la réglette en vue mini

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#40]
Quelques petites propositions :

1. Mettre la réglette en opacité 50%
2. Réduire la marge autour de la réglette (maquette ci-dessous à 10px au lieu de 20px)
3. Mettre la réglette sous le titre du premier cycle

<img width="651" alt="image" src="https://github.com/jean-io/moncycle.app/assets/24638389/2b544f37-1aed-4025-b3af-159da31d3f0e">

4. Le titre et la réglette restent "collés" en haut (pas seulement la réglette)
5. Quand le cycle suivant "arrive", le titre du cycle suivant passe d'abord sous la réglette et "chasse" le titre précédent et la réglette reste en place. Le fait que le titre passe sous la réglette permet de coller la réglette sur le cycle suivant si on veut vraiment voir rapidement quel est le numéro du jour que l'on souhaite regarder.

**Comment by jean-io** [comment]
Bonjour @Limezy, merci pour le retour. Je ne suis pas sur de comprendre le besoin derrière ces propositions d'évolutions. Dans le dernier commit ([22d594a](https://github.com/jean-io/moncycle.app/commit/22d594a2bc0ae732c3ac1e06f9d132b2f777dc28)) le titre de la réglette a été supprimé.

Sur la capture d'écran, la réglette est entre le titre et le cycle j'ai pas compris 😅

**Comment by Limezy** [comment]
Bonjour @jean-io, ce sont des propositions pour améliorer l'esthétisme et le côté pratique de la réglette.
Cette réglette est intéressante mais je trouve qu'elle est très visible et prend beaucoup de place dans l'interface.
La capture d'écran est une maquette pour tenter de montrer ce à quoi pourrait ressembler l'interface en suivant les idées proposées !

**Comment by jean-io** [comment]
Du coup j'ai mis la règle par cycle et masquée par default. Je pense pas mettre de l'opacité pour justement amener plus de lisibilité. @Limezy dis moi si c'est mieux.
![image](https://github.com/jean-io/moncycle.app/assets/4070933/055dc5c1-7666-4081-bcac-3cf357604f59)
