### ISSUE TITLE
Bouttons règles inadaptés

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#45]
Bonjour,

Merci pour la V13 ! Je viens de mettre à jour l'application Yunohost.
Petite suggestion cosmétique pour la v13, en vue "mini"
1. Mettre l'icône "règle" en haut (voir flèche rouge). Cela évite d'avoir une règle sur chaque ligne, ce qui prend pas mal de place visuellement pour une fonction probablement mineure (= utilisée mais rarement)
2. Quand on clique sur l'icône "règle" en haut (devenue unique) alors une règle apparaît en haut et y reste quand on 'scrolle' les cycles en dessous (comme cela était le cas dans une version précédente de moncycle.app)
3. Quand la règle est activée, l'icône change (par exemple jaune ou alors format bouton "enfoncé" avec une ombre) ce qui permet à l'utilisateur de comprendre qu'il s'agit d'une option qu'il peut désactiver en re-cliquant sur la même icône

Cela me semble plus élégant même si ça reste bien sûr une suggestion.
Le seul compromis selon moi, c'est qu'il faut un peu scroller vers le haut si l'on veut précisément voir quel jour était la case d'un vieux cycle. Néanmoins, ceci est probablement un cas très rare, et de toutes façons en vue mini même plusieurs années de cycles sont très rapides à scroller (sur mon iPhone mini, 1 an de cycles en vue mini ~= un écran en hauteur)

<img width="698" alt="Capture d’écran 2024-04-23 à 16 39 33" src="https://github.com/jean-io/moncycle.app/assets/24638389/c247ea34-25d6-4467-98c2-b79321e77d0c">

**Comment by jean-io** [comment]
Bonjour @Limezy merci pour ta suggestion pertinente, comme d'habitude 👍🏻 je suis d'accord que le bouton règles à chaque cycle est lourd visuellement. Personnellement je préfère l'option 2, mais dans ce cas je vois pas l'utilité d'une fonction cacher/afficher la règle, autant la laisser tout le temps visible non ?

**Comment by Limezy** [comment]
Avec plaisir, comme d'habitude !

L'utilité de cacher la règle est de gagner de l'espace vertical en vue mini en n'affichant par défaut que ce qui relève de la fonction essentielle. Cela me semble en effet être un bon principe en matière d'UX de simplifier au maximum et d'ajouter les fonctions non-essentielles comme des "plugins" activables via l'interface pour ceux qui en ont besoin quand ils en ont besoin.

La méthode Billings (je ne connais pas les autres) ne nécessite à aucun moment de pouvoir associer une observation à un jour dans le cycle. Au contraire, même, j'imagine qu'un formateur Billings (que je ne suis pas encore 🤣) conseillerait à un couple débutant de s'écarter d'idées reçues telles que "mon sommet tombe toujours le 14e ou 15e jour du cycle" et de ne se fier qu'aux observations seules. Cela me semble donc aller dans le bon sens que de rendre cette information discrète dans l'interface (jour en gris pâle en vue maxi) ou invisible dans l'interface (vue mini avec règle désactivée).

Le nombre de jours après sommet, lui, est absolument essentiel à la méthode, et ça tombe bien il est affiché très clairement par défaut, même en vue mini, et il n'y a pas d'option pour le désactiver !

**Comment by jean-io** [comment]
@Limezy je cherche à te joindre par tél : peux-tu m'envoyer un message sur Signal `@jean.11` ou m'écrire par mail à bonjour@moncycle.app ? Merci 🙂

**Comment by Limezy** [comment]
👍

**Comment by jean-io** [comment]
Après réflexion, le titre restera la manière d'activer la règle. Je pense aussi masquer les boutons en vue maxi, on pourra retrouver les boutons en cliquant sur le titre aussi. Ca va nécessiter d'éduquer les utilisateurs.
