### ISSUE TITLE
Encore quelques lignes blanches

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#50]
Sur le dernier commit, je vois encore quelques lignes blanches. Elles apparaissent systématiquement entre l'avant dernier et le dernier jour (vue mini et maxi) ou entre le premier et le deuxième jour (vue maxi). Quelques screenshots joints. 

![image](https://github.com/jean-io/moncycle.app/assets/24638389/33451a74-a89a-4ee9-90c7-bbe225f689ca)

![image](https://github.com/jean-io/moncycle.app/assets/24638389/742378ed-7d22-46fa-9565-1bb37ba8ec43)

**Comment by jean-io** [comment]
Est-ce en zoomant ?

**Comment by Limezy** [comment]
Non, c'est un pur screenshot depuis mon iPhone 13 mini. Le zoom vient simplement du recadrage que j'ai fait sur les jours du cycle problématiques. 
Si tu n'arrives pas à reproduire je peux tenter de t'envoyer une séquence qui crée le problème.

**Comment by Limezy** [comment]
> Si tu n'arrives pas à reproduire je peux tenter de t'envoyer une séquence qui crée le problème.

Je n'ai pas eu à chercher loin : le premier jour du premier cycle du compte de démo Billings reproduit la ligne blanche sur mon iPhone 13 mini. Je peux tenter ce soir sur le simulateur.

**Comment by jean-io** [comment]
Merci pour la précision. La question: quelle élément graphique augmente la hauteur ou la largeur de l'observation et crée une ligne blanche à l'intérieur de celle-ci.

**Comment by Limezy** [comment]
L'arrondi ?

**Comment by jean-io** [comment]
c'était au simulateur ou sur iPhone directement ?

**Comment by Limezy** [comment]
Sur l'iPhone. Je vais regarder si ça apparaît aussi sur le simulateur.

**Comment by jean-io** [comment]
De mon coté je n'arrive pas à reproduire.

**Comment by Limezy** [comment]
Je mets à jour sur le dernier commit `main` et je te dis si c'est encore là.
La dernière fois que j'ai testé le bug se produisait sur nos données persos ainsi qu'avec le cycle de démo Billings, sur un iPhone 13 mini sous iOS 16.3.1.

**Comment by Limezy** [comment]
Comme discuté, sur le même téléphone sous iOS 17 et avec le même dataset les lignes blanches n'apparaissent pas... Sur un simulateur iOS 17.5 les lignes blanches n'apparaissent pas.
Je pense que c'est lié à la version webkit de l'OS. Je télécharge le simulateur iOS 16.4 pour voir si j'arrive à reproduire.

**Comment by jean-io** [comment]
Top merci

**Comment by Limezy** [comment]
J'arrive à reproduire le problème avec le simulateur iPhone 14 sous iOS 16.4
<img width="564" alt="image" src="https://github.com/user-attachments/assets/04c60cef-64b4-4bf9-ade6-dcad93d85308">

**Comment by jean-io** [comment]
Dans la mesure ou c'est iOS 16, c'est moins "critique" et ca peut donc attendre la prochaine release.

**Comment by jean-io** [comment]
Il y a tellement d'autre priorité que je ne suis pas sur de travailler sur ce point vu que c'est pour une version antérieur d'iOS et le bug n'est pas très "dérangeant"
