### ISSUE TITLE
Erreur 500 après MAJ en v13

### ISSUE THREAD

**Issue by infocillasas** [jean-io/moncycle.app#51]
Bonjour,
Page (presque) blanche et erreur dans la console suite à mise à jour en v13.
Auriez-vous une idée ?

![Capture d’écran du 2024-06-18 10-30-42](https://github.com/jean-io/moncycle.app/assets/150066394/77e40d10-e81a-4a03-babb-040292cfb76d)
![Capture d’écran du 2024-06-18 10-30-32](https://github.com/jean-io/moncycle.app/assets/150066394/cfc17cdb-4229-4838-be91-24ae39b29cad)
![Capture d’écran du 2024-06-18 10-30-21](https://github.com/jean-io/moncycle.app/assets/150066394/64c5aa76-b8a2-4f83-82d8-f5ba15702b6a)

**Comment by infocillasas** [comment]
**Addendum:** Voici le log d'erreur php dans /var/log/apache2
Pourtant j'avais bien effectué la mise à jour de la DB pour la v10

![image](https://github.com/jean-io/moncycle.app/assets/150066394/d071f161-c59e-4c50-bc08-de351695dcc4)

**Comment by Limezy** [comment]
La colonne "recherche" semble manquer de votre base de données.
https://github.com/jean-io/moncycle.app/blob/60b6ebdab2655c5e8b562a6c46374c4d670fe001/db/migration/v9_vers_v10.sql#L3
C'est à cette ligne de la migration qu'elle aurait dû être créée. Avez-vous accès à votre base avec un logiciel tel que PhPmyadmin ? Si oui, voyez-vous bien cette colonne ?

**Comment by jean-io** [comment]
Il y a clairement un besoin de mise à jour automatique de la base de données à chaque mise à jour 🤔

Comme indiqué par @Limezy l'execution de ce script sql devrait corriger le problème.

**Comment by infocillasas** [comment]
Bonjour,
J'étais persuadé d'avoir fait la MAJ de la BDD lors d'une précédente mise à jour du code.
Après upgrade de la BDD, cela fonctionne
Merci pour vos retours.

**Comment by jean-io** [comment]
Merci pour le retour et la contribution 🙂
