### ISSUE TITLE
Fichier de licence dans le dépôt

### ISSUE THREAD

**Issue by Limezy** [jean-io/moncycle.app#7]
Bonjour, 
Pourriez-vous svp ajouter un fichier de licence ?
Vous faites mention de CC-BY-NC-SA, mais il existe plusieurs versions ! https://spdx.org/licenses/
Le paquet Yunohost ne sera pas inclus dans le catalogue officiel s'ils ne peuvent pas vérifier la licence de ce dépôt "upstream"

**Comment by Thovi98** [comment]
J’étais en train de parcourir le dépôt des applications de Yunohost, et je suis tombé sur cette app 🤩 (Merci @Limezy d’avoir commencé à la packagé, j’ai trop hâte !)

En ce qui concerne la licence, le Readme renvoie à la version 4.0 dans le lien.

Je propose d’ajouter la licence directement dans le projet, comme le font la majorité des projets open source, si @jean-io y trouve aussi un intérêt.

**Comment by jean-io** [comment]
Merci @Thovi98 oui il y a clairement un intérêt
